#!/usr/bin/env python3
#
# Copyright (C) 2014  Jon Dufresne <jon.dufresne@gmail.com>
#
# This program is free software: you can redistribute it and/or modify
# it under the terms of the GNU General Public License as published by
# the Free Software Foundation, either version 3 of the License, or
# (at your option) any later version.
#
# This program is distributed in the hope that it will be useful,
# but WITHOUT ANY WARRANTY; without even the implied warranty of
# MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
# GNU General Public License for more details.
#
# You should have received a copy of the GNU General Public License
# along with this program.  If not, see <http://www.gnu.org/licenses/>.
import os
import re
import site
from importlib import import_module

from django.apps import apps
import django

django.setup()


def in_site_packages(path):
    return any(
        path.startswith(site_path)
        for site_path in site.getsitepackages())


def is_load_used_in_template(f, tag_filters):
    tags, filters = tag_filters

    f.seek(0)
    for line in f:
        for tag in tags:
            if re.search(r'{%%\s*%s' % re.escape(tag), line):
                return True
        for tag in filters:
            if re.search(r'\|\s*%s' % re.escape(tag), line):
                return True

    return False


def lib_template_tags(lib):
    for app in apps.get_app_configs():
        path = '%s.templatetags.%s' % (app.module.__name__, lib)
        try:
            mod = import_module(path)
        except ImportError:
            pass
        else:
            return mod.register.tags.keys(), mod.register.filters.keys()
    path = 'django.templatetags.%s' % lib
    try:
        mod = import_module(path)
    except ImportError:
        raise ImportError('ImportError: No templatetag module named %s' % lib)
    else:
        return mod.register.tags.keys(), mod.register.filters.keys()


def template_unused_loads(path):
    regex = re.compile('{%\s*load\s+(\w+)')
    libs = {}
    with open(path) as f:
        for line in f:
            match = regex.search(line)
            if match:
                lib = match.group(1)
                if lib != 'static':
                    libs[lib] = lib_template_tags(lib)
        for lib, tags in libs.items():
            if not is_load_used_in_template(f, tags):
                print('%s: %s' % (path, lib))


def search_dir_unused_loads(path):
    for dirpath, dirnames, filenames in os.walk(path):
        for filename in filenames:
            path = os.path.join(dirpath, filename)
            template_unused_loads(path)


def search_dir_used_tag(path, tag):
    regex = re.compile('{%%\s*%s' % re.escape(tag))
    for dirpath, dirnames, filenames in os.walk(path):
        for filename in filenames:
            path = os.path.join(dirpath, filename)
            with open(path) as f:
                for line in f:
                    if regex.search(line):
                        return True
    return False


def is_tag_used_in_templates(tag):
    from django.conf import settings

    for template_settings in settings.TEMPLATES:
        for path in template_settings['DIRS']:
            if search_dir_used_tag(path, tag):
                return True
    for app in apps.get_app_configs():
        path = app.path
        if not in_site_packages(path):
            if search_dir_used_tag(os.path.join(path, 'templates'), tag):
                return True
    return False


def main():
    from django.conf import settings

    print('Unused templatetag loads:')
    for template_settings in settings.TEMPLATES:
        for path in template_settings['DIRS']:
            search_dir_unused_loads(path)

    for app in apps.get_app_configs():
        path = app.path
        if not in_site_packages(path):
            search_dir_unused_loads(os.path.join(path, 'templates'))

    print('Unused templatetags:')
    for app in apps.get_app_configs():
        path = os.path.join(app.path, 'templatetags')
        if not in_site_packages(path):
            for dirpath, dirnames, filenames in os.walk(path):
                for filename in filenames:
                    if filename.endswith('.py') and filename != '__init__.py':
                        lib, ext = os.path.splitext(filename)
                        for tag in lib_template_tags(lib)[0]:
                            if not is_tag_used_in_templates(tag):
                                print('%s: %s' % (os.path.join(path, filename), tag))


if __name__ == '__main__':
    main()
